name: MyFirstActionScript
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
  another-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install latest CMake and Ninja
        uses: lukka/get-cmake@latest
        
      - name: Install VCPKG
        run: |
          cmake --version
          git clone https://github.com/microsoft/vcpkg.git
          cd VCPKG
          ./bootstrap-vcpkg.sh
        
      - name: Install VCPKG packages
        run: |
          vcpkg install curl miniz zlib